baseURL = "https://benfarley.dev/"
languageCode = "en-gb"
theme = "m10c"
title = "Ben's Blog"
enableEmoji = true

# Theme Params
[params]
	author = "Benjamin Farley"
    description = "Platform Engineer, Father, Cyclist"
    dateformat = "Jan 2, 2006"

# Social Settings
  [[params.social]]
    name = "github"
    url = "https://github.com/BenjaminFarley"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/Ben_Farley44"